# Generated by Django 3.2.5 on 2023-01-31 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20230131_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveIntegerField(blank=True, choices=[(2, 'Customer'), (1, 'Restaurant')], null=True),
        ),
    ]
